### ISSUE TITLE
enable pre-commit as a blocking check

### ISSUE THREAD

**Issue by jope35** [jope35/pumaplot#16]
## Description
run the pre-commit hooks as a required check in GitHub actions

## Tasks
 
- [ ] create .github/actions.yml
- [ ] trigger it on each pr
- [ ] make it a blocking requirement 
 
 
## Acceptance criteria

- [ ] For each push on an open pr, the pre-commit hook needs to be run
- [ ] All checks of the pre-commit hook need to pass
