### ISSUE TITLE
setup a dummy time series generator 

### ISSUE THREAD

**Issue by jope35** [jope35/pumaplot#18]
## Description
 to aid development, a dummy time-series generator will be used for future development

## Tasks
 
- [ ] investigate how to integrate dummy data 
- [ ] determine how to generate static dummy data 
 
 
## Acceptance criteria

- [ ]  a function that generates dummy data in a static manner
 
 
## Extra
keep in mind that this dummy generator can also be used to perform unit/e2e testing
